### ISSUE TITLE
Survey form and raw data reports caching review

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-services#115]
We need to investigate the caching functionality to ensure it works as expected, while addressing the necessary use cases.  We have had a lot of issues where people are retrieving cached survey forms and it causes the perception that they may have lost some data or edits

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5832](http://flowhelp.akvo.org/discussions/problems/5832-request-for-support).
