### ISSUE TITLE
Update export raw text file functionality so that it supports RQGs

### ISSUE THREAD

**Issue by rumca** [akvo/akvo-flow-services#119]
I've just noticed that the "Export raw text file" option on the reports page is no longer working as intended. The survey headers are being populated in the report correctly, but none of the responses are present. After chatting with @jonase it seems that this is something I missed for the testing on 1.9.1 and it will require some work to update with the RQG export feature.

@muloem if it's not currently being utilised (assuming it's not given that there have been no support requests about it?) then perhaps this functionality should just be removed instead of updated?

**Comment by jonase** [comment]
One approach would be to generate the excel file, read it row-by-row and and generate the text file that way. This would keep the two report types in sync.

**Comment by janagombitova** [comment]
After discussing this issue today we agreed to leave it as it is for the time being. Once a support request or other remark from the user comes in we will deal with it.
