### ISSUE TITLE
Bulk upload does not work

### ISSUE THREAD

**Issue by valllllll2000** [akvo/akvo-flow-services#155]
Steps to reproduce:
Fill out some surveys on mobile device in flight mode
Once they are in exported state zip the data folder inside akvoflow, call it dataz.zip
Pull dataz.zip on PC
Using chrome browser I have tried to upload data.zip via the data/bulk upload data tab
In messages I can see the file as processed.
Here is the stacktrace of the issue:
`Caused by: java.lang.IllegalArgumentException: /data/files/58cffa26-3f9b-4479-b772-ef10ef9fc50d.zip is not a relative path	at clojure.java.io$as_relative_path.invoke(io.clj:405)	at clojure.java.io$file.invoke(io.clj:416)	at clojure.lang.AFn.applyToHelper(AFn.java:156)	at clojure.lang.RestFn.applyTo(RestFn.java:132)	at clojure.core$apply.invoke(core.clj:632)	at me.raynes.fs$file.doInvoke(fs.clj:56)	at clojure.lang.RestFn.invoke(RestFn.java:423)	at me.raynes.fs.compression$unzip$target_file__4141.invoke(compression.clj:18)	at me.raynes.fs.compression$unzip.invoke(compression.clj:20)	at akvo.flow_services.uploader$unzip_file.invoke(uploader.clj:80)	at akvo.flow_services.uploader$bulk_upload.invoke(uploader.clj:258)	at akvo.flow_services.scheduler.BulkUploadJob.execute(scheduler.clj:73)	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)`

**Comment by iperdomo** [comment]
> Once they are in exported state zip the data folder inside akvoflow, call it dataz.zip
> Pull dataz.zip on PC

you see that your zip file has an __absolute__ path to `/data/` which doesn't exist on the server.

**Comment by valllllll2000** [comment]
After talking to @iperdomo he has found the issue: 
The zip file I am trying to upload has absolute paths, it was generated by an App I have on my device, called ASTRO:
https://dpaste.de/eRA5/raw
A zip file generated by the PC has the following structure:
https://dpaste.de/0V1T/raw
In my opinion flow-services should be able to read both files but if it si decided that this is not a bug, we should explain in the testing plan about this and inform the users that the zip file has to be generated by a computer and not any mobile app.

**Comment by muloem** [comment]
@valllllll2000 I think it shouldn't matter where the zip file is generated so I think we can keep this recorded as a bug and fix it. 👍

**Comment by iperdomo** [comment]
@valllllll2000 we do inform the users to use a computer zip program - http://flowsupport.akvo.org/article/show/bulk-upload-data-tab
