### ISSUE TITLE
Expose version information for sevices.

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-services#162]
It would be useful to have a simple way to see what version of Flow services is deployed to the test and live servers.
At a minimum it should be saved in a file during deployment or compiled into the uberjar.
It would also be good if it was written in the log files so that it is clear afterwards what version was running when an error occurred.

**Comment by stellanl** [comment]
For the backend, the __VERSION__ token in footer.handlebars is replaced after it has been rolled into app.js by version information from "git describe" by the ant buildfile, GAE/build.xml
In services, the exporterjar is installed by maven, with the version as a define, and is perhaps 
extractable later.

**Comment by stellanl** [comment]
Version information is available in the project.clj file, that is in the root of the uberjar.
From Java, it could be accessed roughly like this:
InputStream in = getClass().getResourceAsStream("/project.clj");

**Comment by dlebrero** [comment]
The Kubernetes flow-services pod has the git sha:

![screen shot 2018-04-26 at 16 29 20](https://user-images.githubusercontent.com/2147539/39312373-b41670ae-496f-11e8-921d-be0def61316a.png)

Is this enough?
