### ISSUE TITLE
Read caddisfly tests file URL option from configuration

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-services#168]
The caddisfly test file URL can be optionally added to a configuration file of an app engine instance.  We need to read this configuration and load it in case it is present to that the correct caddisfly tests are included in the generated report.

**Comment by muloem** [comment]
## Test Plan

* All regression tests with caddisfly should operate as before.

**Comment by janagombitova** [comment]
All works as expected. ready to roll 👍
