### ISSUE TITLE
Check validation of the survey during import

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-services#173]
When importing a survey, we validate the survey being imported by checking that the IDs of the questions (found in the spreadsheet header row) are a subset of the questions that are used in the survey.  However, we use the latest state of the survey rather than the latest _published_ state of the survey to check this.  For cases where questions have been added to the survey, this check works but it should fail for cases where questions have been deleted from the survey. 

In the change planned in https://github.com/akvo/akvo-flow/issues/2285, we will use the latest published version of the survey, but we need to decide then how the validation of the import works in this case.

**Comment by stellanl** [comment]
The Java-centric solution is to drop this check from the Clojure code, and add it to the validate() method as part of #3093.
