### ISSUE TITLE
Geoshape exports do not give all repeats for repeated groups 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-services#245]
# Context

Every Flow form consists of question groups that hold questions. To create a user friendly version of the commonly use tabular questions that works on a screen of the phone we introduced repeated question groups. A repeated question group is a question group that the enumerator can repeatedly ask any number of times. This question group can hold any types of questions also geographical shapes. 
 
Salim can export data based on the geographic shape question in a json format to then use in a GIS tool easily. In the last changes we made sure he can export polygons as well as points and lines. 

When exporting repeated groups Salim has two options. Data cleaning export makes a separate sheet for each group and then every repetition is in its own row. Data analysis export holds the entire data set in one sheet thus each repetition is in its own row with the meta data copied over to all rows.
 
# Issue 
It seems that the geoshape export only holds the 1st repetition of a repeated question group (the 1st row) and not the following ones. 

# Solution
Make sure geoshape exports hold all answers, also from repeated groups and are marked correctly with the repeat number. 

# Created via Reamaze:
More detials on the issue can be found here. 
Link: https://akvoo.reamaze.com/admin/conversations/akvoflow-support-request-number-165028-from-geert-at-akvo-dot-org

**Comment by janagombitova** [comment]
@dlebrero As you have handled the last issue related to geoshape exports, can you take a look at this one too? Thanks

**Comment by dlebrero** [comment]
I do not have access to Reamaze, so I cannot look at the response structure that Geert is proposing. Could you please add the details about the proposed structure here?

**Comment by janagombitova** [comment]
I have sent you an invite to reamaze

**Comment by janagombitova** [comment]
[combined_with_.txt](https://github.com/akvo/akvo-flow-services/files/2778031/combined_with_.txt)

@dlebrero here is the file from Geert holding the export example with the repeated groups that Joy generated for him

**Comment by dlebrero** [comment]
Thanks @janagombitova. Is it ok to have that file in the open?

**Comment by dlebrero** [comment]
I see that the file actually contains two different "repeats" that flow services do not support:

1. Repeated question groups
1. Multiple geoshapes within one geoshape answer

## Repeated question groups
Flow services [is filtering response that is not for iteration 0](https://github.com/akvo/akvo-flow-services/blob/61acb8eeb2f8c7dcfa43e3843413fda6f30fc9db/backend/src/akvo/flow_services/geoshape_export.clj#L162).

To fix, we will stop this filtering and we will add a new property "Repeat no".

## Multiple geoshapes within one geoshape answer

Flow services always [extracts the first feature](https://github.com/akvo/akvo-flow-services/blob/61acb8eeb2f8c7dcfa43e3843413fda6f30fc9db/backend/src/akvo/flow_services/geoshape_export.clj#L58)  from the geoshape answer, ignoring any other geoshapes.

To fix, we will generate one new "feature" for each geoshape within a geoshape answer.

@joycarpediem can you please confirm that this is what we want?

**Comment by dlebrero** [comment]
Done the first part. 

Waiting for confirmation about the second bit.

**Comment by janagombitova** [comment]
@dlebrero as Joy has not reacted so far, can we push forward the changes you have made and leave the rest (filtering multiple geoshapes within one answer) untouched?

**Comment by dlebrero** [comment]
Created a PR to fix the "Repeated question groups" bit.
