### ISSUE TITLE
Different email for statistics report

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-services#272]
Services part of akvo/akvo-flow#2612
The current email is not quite suitable for the statistics report as it is not downloaded from the same page as the data exports. I can supply the text but a Clojure person needs to figure out the switching logic.

**Comment by stellanl** [comment]
So the new strings 
_statistics_header and _statistics_gdpr_body 
are to be used for a report of type STATISTICS.

The old strings _report_header and _report_gdpr_body
have been renamed to _export_header and _export_gdpr_body
and are to be used for the other reports.

**Comment by stellanl** [comment]
Maybe the simplest solution is to have a subject/body pair of resources for each export type. So one _comprehensive_header , one _data_cleaning_header  and one _statistics_header etc.

**Comment by janagombitova** [comment]
@stellanl why have different emails per each export type, if we only need two - one that points the user to the Export data tab and one to the Stats tab?

**Comment by stellanl** [comment]
That way you would not even have to be a programmer to change them. There would be one message for each type of export and you could change or add to them without having to change the Clojure code at all.
