### ISSUE TITLE
JSON serialization

### ISSUE THREAD

**Issue by ichinaski** [akvo/akvo-flow-services#98]
# Overview

Add support for new JSON-based data files. Similar to the approach taken in GAE, the bulk ingestion process should browse the contents of the zip file, and determine whether to use JSON or TSV in order to proceed with the data ingestion.

Relevant GAE issue: https://github.com/akvo/akvo-flow/issues/1247

**Comment by ichinaski** [comment]
**Test plan:**
* Perform a bulk upload with the new app (JSON-formatted data).
* Perform a bulk upload with v2.1.5 (TSV-formattted data).
* Perform a bulk upload with v1.13.X (TSV-formatted data).

**Note: make sure exported data contains media files (images or videos)**

**Comment by rumca** [comment]
the above test cases pass fine
